-- MySQL Script generated by MySQL Workbench
-- Sat Mar  1 15:59:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sq-pm
-- -----------------------------------------------------
-- slicequeue 프로젝트 관리 스키마

-- -----------------------------------------------------
-- Schema sq-pm
--
-- slicequeue 프로젝트 관리 스키마
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `sq-pm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `sq-pm`;

-- -----------------------------------------------------
-- Table `sq-pm`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sq-pm`.`account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '계정 일련번호',
  `email` VARCHAR(256) NOT NULL COMMENT '계정 이메일',
  `pwd` VARCHAR(1024) NOT NULL COMMENT '계정 비밀번호',
  `nickname` VARCHAR(128) NULL COMMENT '계정 별명',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '생성 일시',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정 일시',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unq_acc_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '계정';


-- -----------------------------------------------------
-- Table `sq-pm`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sq-pm`.`project` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '프로젝트 일련번호',
  `name` VARCHAR(128) NOT NULL COMMENT '프로젝트명',
  `code` VARCHAR(64) NOT NULL COMMENT '프로젝트 코드',
  `account_id` BIGINT NOT NULL COMMENT '관리자 일련번호',
  `start_at` DATETIME NOT NULL COMMENT '프로젝트 시작 일시',
  `end_at` DATETIME NOT NULL COMMENT '프로젝트 종료 일시',
  `memo` VARCHAR(10000) NULL COMMENT '프로젝트 메모',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '생성 일시',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '수정 일시',
  PRIMARY KEY (`id`),
  INDEX `fk_prj_account_id_acc_id` (`account_id` ASC) INVISIBLE,
  UNIQUE INDEX `unq_prj_code` (`code` ASC) VISIBLE,
  INDEX `idx_prj_account_id_start_at_end_at` (`account_id` ASC, `start_at` ASC, `end_at` ASC) INVISIBLE,
  CONSTRAINT `fk_prj_account_id_acc_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `sq-pm`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '프로젝트';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE `sq-pm`.`account` 
ADD COLUMN `refresh_token` VARCHAR(36) NULL COMMENT '계정 리프레시토큰' AFTER `nickname`,
ADD COLUMN `refresh_token_expired_at` DATETIME(3) NULL COMMENT '리프레시토큰 만료일시' AFTER `refreshToken`;

ALTER TABLE `sq-pm`.`account`
CHANGE COLUMN `email` `email` VARCHAR(255) NOT NULL COMMENT '계정 이메일' ,
CHANGE COLUMN `pwd` `pwd` VARCHAR(255) NOT NULL COMMENT '계정 비밀번호' ;

ALTER TABLE `sq-pm`.`project`
ADD COLUMN `deleted_at` DATETIME(3) NULL COMMENT '삭제 일시' AFTER `memo`;
