server:
  port: 8080

spring:
  application:
    name: sq-project-manager
  datasource:
    url: ${DB_URL:"jdbc:mysql://localhost:3306/sq-pm"}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate


jwt:
  secret-key: ${JWT_SECRET_KEY:default-secret-key}
  expiration-time: ${JWT_EXPIRATION_TIME:1800000}
